export {default as About} from "./About/About"
export { default as Body } from './Body/Body'
export {default as Cart} from './Cart/Cart'
export { default as Header } from './Header/Header'
export { default as FAQs } from './FAQs/FAQs'
export { default as Search } from './Search/Search'
export { default as Error } from './Error/Error'
export {default as Contact} from './Contact/Contact'
export {default as RestaurantsMenu} from './RestaurantsMenu/RestaurantsMenu'
export {default as Shimmer} from './Shimmer/Shimmer'
export {default as SpinnerEffect} from './SpinnerEffect/SpinnerEffect'